### ISSUE TITLE
Not quite there..

### ISSUE THREAD

**Issue by pacmac** [maxexcloo/DNS-Tunnel#1]
Firstly, thanks so much for this.

I already had dnsmasq and sniproxy installed on my VPS, but followed your install instructions and the install script seemed to complete successfully, and the /etc/dnstun/host and client files were created with the correct data as setup in gist.

I have set the vps's ip address in my client DNS settings, and running the dig command followed by one of the urls in the hosts file (www.speedtest.net) shows that the dns request was replied by my server running dnsmasq.

However when I open the url in my browser http://www.speedtest.net, the geo-location is still pulling my nearest speedtest.net server rather than the ones in the UK where my VPS is located.

 I looked at the sniproxy logs ( /var/log/sniproxy/http_access.log ) no requests i.e  (http://www.speedtest.net) are being forwarded to sniproxy.

Any suggestions on how I can debug what may be wrong ??

**Comment by maxexcloo** [comment]
Any chance you can share your configuration? Speedtest may use some other
domain for geolocation

**Comment by pacmac** [comment]
Sure, but the same same thing with bbc:

##/etc/dnstun/client

```
home.myhomedomain.com
```

##/etc/dnstun/host

```
bbc.co.uk
www.speedtest.net
```

##/etc/sniproxy.conf

```
pidfile /var/tmp/sniproxy.pid
user daemon

listener 80 {
    proto http
}

listener 443 {
    proto tls
}

table {
bbc.co.uk *
speedtest.net *
}
```

##/etc/dnsmasq.conf

```
bogus-priv
domain-needed
no-poll
no-resolv
server=8.8.8.8
server=8.8.4.4
address=/bbc.co.uk/172.27.224.1
172.27.228.1
172.27.232.1
172.27.236.1
185.35.77.179
185.35.77.145
address=/www.speedtest.net/172.27.224.1
172.27.228.1
172.27.232.1
172.27.236.1
185.35.77.179
185.35.77.145
```

**Comment by maxexcloo** [comment]
I'm curious, can you add flagfox.net to the hosts list then visit
group.flagfox.net in a browser? If that works I'd guess its a quirk with
how speedtest works and I'll have to do some testing tomorrow (its late
here unfortunately)

**Comment by pacmac** [comment]
I get a "Server Not Found Error", also I noticed the following message when re-applying the gists:

```
 * Restarting DNS forwarder and DHCP server configuration syntax check                                                                             [fail] 
2014-09-10 15:18:08 Parsed bbc.co.uk *
2014-09-10 15:18:08 Parsed www.speedtest.net *
2014-09-10 15:18:08 Parsed flagfox.net *
iptables v1.4.21: host/network `' not found
Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by pacmac** [comment]
```
pacbook-5:~ pac$ nslookup group.flagfox.net
Server:     xxx.xx.77.179
Address:    xxx.xx.77.179#53
** server can't find group.flagfox.net: NXDOMAIN
```

xxx.xx.77.179 is my VPS in the UK

```
root@UBU12:~# netstat -tulpn | grep :80
tcp6       0      0 :::80                   :::*                    LISTEN      3181/sniproxy  

root@UBU12:~# netstat -tulpn | grep :443
tcp6       0      0 :::443                  :::*                    LISTEN      3181/sniproxy
```

**Comment by maxexcloo** [comment]
Curious, your dnsmasq config shouldn't contain all those random IPs, only
your main IP on each address line, I'll have to test it (if you find the
issue though a pull request is appreciated though)

Also it should be geoip.flagfox.net (autocorrect grrr), sorry about that
typo.

**Comment by pacmac** [comment]
Thanks for helping, it's late here too so I don't think I will do anything else tonight.

geoip.flagfox.net works, but shows my location as Singapore (where I am) rather than the UK where my VPS is.

Thanks again

**Comment by pacmac** [comment]
OK, the reason that so many ip addresses are listed in dnsmasq is because those are all of the interfaces on the vps, some were created by openvpnas which is now disabled and I am now left with just 2, eth0 and eth1.

When I run the script, both ip addresses are added to dnsmasq by the script, so I have manually edited and re-started dnsmasq to include only the ip address for eth0:

  bogus-priv
  domain-needed
  no-poll
  no-resolv
  address=/bbc.co.uk/xxx.xx.77.179
  address=/www.speedtest.net/xxx.xx.77.179
  address=/flagfox.net/xxx.xx.77.179
  server=8.8.8.8
  server=8.8.4.4

But unfortunately, that has not solved the problem, the dns requests from the client is being answered with the ip address of the VPS, and sniproxy is running, but the requests do not appear to being passed to sniproxy.

I also have a difference in my setup as I am using UFW and not iptables, but I do have forwarding enabled and it works just fine with forwarding packets though squid.

I am continuing to investigate...
