### ISSUE TITLE
nice!

### ISSUE THREAD

**Issue by tvvocold** [maxexcloo/DNS-Tunnel#2]
if i wanna open google.com(which china gov block them）in china, will DNS-Tunnel work?

**Comment by maxexcloo** [comment]
Probably! Why not give it a try?

**Comment by tvvocold** [comment]
so cool!
it works.
btw,what's the "user" in gist mean?(i just put my local ip in it)

**Comment by tvvocold** [comment]
can i make it for public use?(like set the local ip to _._._._ so that all my friends could use it?)

**Comment by tvvocold** [comment]
iptables v1.4.14: host/network `' not found Try`iptables -h' or 'iptables --help' for more information.
